# https://taskfile.dev
# Scale Daemon - Task Runner
# Source of Truth for Naming Conventions

version: '3'

silent: true

vars:
  # ===========================================================================
  # 📝 CONFIGURATION & NAMING (SOURCE OF TRUTH)
  # ===========================================================================

  # Directories
  BIN_DIR: ./bin
  TMP_DIR: ./tmp

  # 1. Internal Go Build Paths
  # Where the service binary is placed temporarily for embedding.
  # NOTE: embedded.go EXPECTS this exact path. Do not change without updating embedded.go
  EMBED_SOURCE_PATH: ./tmp/BasculaServicio.exe

  # 2. Installer Output Filenames
  # The final name of the installer executable provided to the user.
  INSTALLER_EXE_LOCAL: R2k_Instalador_Bascula_Local.exe
  INSTALLER_EXE_REMOTE: R2k_Instalador_Bascula_Remote.exe

  # 3. Windows Service Configuration (Injected via ldflags)
  # These control how the service appears in Windows (Task Manager / Services.msc)

  # --- REMOTE ---
  # Service ID in Registry (sc query NAME)
  SVC_ID_REMOTE: "R2k_Bascula_Remote"
  # Display Name in Services.msc
  SVC_DISPLAY_REMOTE: "R2k Bascula Service (REMOTE)"
  # The actual .exe filename on the user's disk (Task Manager Process Name)
  SVC_EXE_NAME_REMOTE: "R2k_BasculaServicio_Remoto.exe"
  # Service name for logging (matches log directory convention)
  SVC_LOG_NAME_REMOTE: "R2k_BasculaServicio_Remote"

  # --- LOCAL ---
  SVC_ID_LOCAL: "R2k_Bascula_Local"
  SVC_DISPLAY_LOCAL: "R2k Bascula Service (LOCAL)"
  SVC_EXE_NAME_LOCAL: "R2k_BasculaServicio_Local.exe"
  # Service name for logging (matches log directory convention)
  SVC_LOG_NAME_LOCAL: "R2k_BasculaServicio_Local"

  # --- CONSOLE ---
  CMD_ID_REMOTE: "R2k_BasculaCmd_Remote"
  CMD_EXE_NAME_REMOTE: "R2k_BasculaConsole_Remote.exe"
  CMD_ID_LOCAL: "R2k_BasculaCmd_Local"
  CMD_EXE_NAME_LOCAL: "R2k_BasculaConsole_Local.exe"

  # Versioning
  VERSION: '1.2.0'

env:
  CGO_ENABLED: '0'
  GOOS: windows
  GOARCH: amd64

tasks:
  default:
    desc: "📋 Show all available tasks"
    cmds:
      - task --list-all

  deps:
    desc: "📦 Download Go dependencies"
    cmds:
      - go mod download && go mod tidy
      - echo "✅ Dependencies ready"

  # ===========================================================================
  # 🏗️ SERVICE BUILDERS (INTERMEDIATE STEP)
  # ===========================================================================
  # These tasks compile the service and place it where the Installer expects it.

  ws:prepare:
    desc: "🛠️ Prepare TMP directory"
    cmds:
      - mkdir -p {{.TMP_DIR}}
      - touch {{.EMBED_SOURCE_PATH}}
      - echo "✅ TMP directory ready at:{{.TMP_DIR}}"
      - mkdir -p {{.BIN_DIR}}
      - echo "✅ BIN directory ready at:{{.BIN_DIR}}"

  service:build:console:
    desc: "🔨 Compile Service with CONSOLE configuration"
    deps: [ ws:prepare ]
    vars:
      BUILD_DATE: { sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'" }
      BUILD_TIME: { sh: powershell -Command "Get-Date -Format 'HH:mm:ss'" }
    cmds:
      # INJECTION: We pass the Names directly to the Go code here
      - go build -ldflags "-X main.BuildEnvironment=local -X main.BuildDate={{.BUILD_DATE}} -X main.BuildTime={{.BUILD_TIME}}" -o {{.BIN_DIR}}/{{.CMD_EXE_NAME_LOCAL}} ./cmd/BasculaServicio
      - echo "✅ Console (LOCAL) compiled to:{{.BIN_DIR}}/{{.CMD_EXE_NAME_LOCAL}}"
      - go build -ldflags "-X main.BuildEnvironment=remote -X main.BuildDate={{.BUILD_DATE}} -X main.BuildTime={{.BUILD_TIME}}" -o {{.BIN_DIR}}/{{.CMD_EXE_NAME_REMOTE}} ./cmd/BasculaServicio
      - echo "✅ Console (REMOTE) compiled to:{{.BIN_DIR}}/{{.CMD_EXE_NAME_REMOTE}}"

  service:build:local:
    desc: "🔨 [INTERNAL] Compile Service with LOCAL configuration"
    internal: true  # Hides from task --list
    deps: [ ws:prepare ]
    vars:
      BUILD_DATE: { sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'" }
      BUILD_TIME: { sh: powershell -Command "Get-Date -Format 'HH:mm:ss'" }
    cmds:
      - mkdir -p {{.TMP_DIR}}
      # INJECTION: We pass the Names directly to the Go code here
      - go build -ldflags "-s -w -H=windowsgui -X main.BuildEnvironment=local -X main.ServiceName={{.SVC_LOG_NAME_LOCAL}} -X main.BuildDate={{.BUILD_DATE}} -X main.BuildTime={{.BUILD_TIME}}" -o {{.EMBED_SOURCE_PATH}} ./cmd/BasculaServicio
      - echo "✅ Service (LOCAL) compiled to temporary path:{{.EMBED_SOURCE_PATH}}"
      - cp {{.EMBED_SOURCE_PATH}} {{.BIN_DIR}}/{{.SVC_EXE_NAME_LOCAL}}
      - echo "✅ Service (LOCAL) copied to embed path:{{.TMP_DIR}}/{{.SVC_EXE_NAME_LOCAL}}"

  service:build:remote:
    desc: "🔨 [INTERNAL] Compile Service with REMOTE configuration"
    internal: true
    deps: [ ws:prepare ]
    vars:
      BUILD_DATE: { sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'" }
      BUILD_TIME: { sh: powershell -Command "Get-Date -Format 'HH:mm:ss'" }
    cmds:
      - mkdir -p {{.TMP_DIR}}
      # INJECTION: We pass the Names directly to the Go code here
      - go build -ldflags "-s -w -H=windowsgui -X main.BuildEnvironment=remote -X main.ServiceName={{.SVC_LOG_NAME_REMOTE}} -X main.BuildDate={{.BUILD_DATE}} -X main.BuildTime={{.BUILD_TIME}}" -o {{.EMBED_SOURCE_PATH}} ./cmd/BasculaServicio
      - echo "✅ Service (REMOTE) compiled to temporary path:{{.EMBED_SOURCE_PATH}}"
      - cp {{.EMBED_SOURCE_PATH}} {{.BIN_DIR}}/{{.SVC_EXE_NAME_REMOTE}}
      - echo "✅ Service (REMOTE) copied to embed path:{{.TMP_DIR}}/{{.SVC_EXE_NAME_REMOTE}}"

  # ===========================================================================
  # 📦 INSTALLER BUILDERS (FINAL ARTIFACT)
  # ===========================================================================

  installer:local:
    desc: "📦 Build Installer (Local/Dev)"
    deps: [ service:build:local ]
    vars:
      BUILD_DATE: { sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'" }
      BUILD_TIME: { sh: powershell -Command "Get-Date -Format 'HH:mm:ss'" }
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags "-s -w -X main.BuildEnvironment=local -X main.ServiceName={{.SVC_ID_LOCAL}} -X \"main.ServiceDisplayName={{.SVC_DISPLAY_LOCAL}}\" -X main.ServiceExeName={{.SVC_EXE_NAME_LOCAL}} -X main.BuildDate={{.BUILD_DATE}} -X main.BuildTime={{.BUILD_TIME}}" -o {{.BIN_DIR}}/{{.INSTALLER_EXE_LOCAL}} ./cmd/BasculaInstalador
      - echo "📦 Created:{{.BIN_DIR}}/{{.INSTALLER_EXE_LOCAL}}"

  installer:remote:
    desc: "📦 Build Installer (Remote/Prod)"
    deps: [ service:build:remote ]
    vars:
      BUILD_DATE: { sh: powershell -Command "Get-Date -Format 'yyyy-MM-dd'" }
      BUILD_TIME: { sh: powershell -Command "Get-Date -Format 'HH:mm:ss'" }
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags "-s -w -X main.BuildEnvironment=remote -X main.ServiceName={{.SVC_ID_REMOTE}} -X \"main.ServiceDisplayName={{.SVC_DISPLAY_REMOTE}}\" -X main.ServiceExeName={{.SVC_EXE_NAME_REMOTE}} -X main.BuildDate={{.BUILD_DATE}} -X main.BuildTime={{.BUILD_TIME}}" -o {{.BIN_DIR}}/{{.INSTALLER_EXE_REMOTE}} ./cmd/BasculaInstalador
      - echo "📦 Created:{{.BIN_DIR}}/{{.INSTALLER_EXE_REMOTE}}"

  # ===========================================================================
  # 🚀 COMMANDS
  # ===========================================================================
  build:local:
    desc: "🏠 Full Build for LOCAL"
    cmds:
      - task: installer:local
      - echo "✅ LOCAL Build Complete"

  build:remote:
    desc: "🌐 Full Build for REMOTE"
    cmds:
      - task: installer:remote
      - echo "✅ REMOTE Build Complete"

  build:console:
    desc: "🖥️ Build CONSOLE versions"
    cmds:
      - task: service:build:console
      - echo "✅ CONSOLE Build Complete"

  build:all:
    desc: "🏗️ Build BOTH environments"
    cmds:
      - task: build:console
      - task: build:local
      - task: build:remote
      - echo "✅ All builds complete"

  clean:
    desc: "🧹 Cleanup"
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -rf {{.TMP_DIR}}
      - echo "✅ Clean complete"